server:
  port: 8761

#spring:
#  application:
#    name: eureka-server-8761  # 应用名称
#eureka:
#  server:
#    eviction-interval-timer-in-ms: 10000  # 服务端间隔多少毫秒做定期删除的操作
#    renewal-percent-threshold: 0.85 # 续约百分比 超过85%的应用没有和你续约 那么eureka会保护服务不会剔除任何一个
#  instance:
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname: loclhost

